CREATE TABLE subscriptions(
	id			INTEGER PRIMARY KEY,
	endpoint	VARCHAR(255) NOT NULL,
	publicKey	VARCHAR(255) NOT NULL,
	authToken	VARCHAR(255) NOT NULL,
	created_at	DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at	DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);
